"""add expires_at to polls

Revision ID: 5448e0667427
Revises: fc2e34e3b8ab
Create Date: 2026-09-13 00:47:27.833664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5448e0667427'
down_revision: Union[str, Sequence[str], None] = 'fc2e34e3b8ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('polls', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('polls', 'expires_at')
    # ### end Alembic commands ###
